spring.application.name=devinci-backend

server.port=${PORT:9090}

spring.datasource.url=jdbc:postgresql://aws-1-ap-northeast-1.pooler.supabase.com:5432/postgres
spring.datasource.username=postgres.kztnblafytwqxwirklzy
spring.datasource.password=devkaranyadavmilli

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

jwt.secret=devinci-super-secret-key-256-bit-length-for-hmac-sha-algorithm-123456
jwt.expiration=86400000